varretObj={
    "status": "0",
    "msg": {
        "total": "72",
        "totalpage": "1",
        "page": "1",
        "result": [
            {
                "bMatchId": "8854",
                "bMatchName": "T1 vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "692",
                "ScoreA": "1",
                "TeamB": "843",
                "ScoreB": "0",
                "MatchDate": "2022-05-10 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46253",
                "HighlightsId": "46270",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8855",
                "bMatchName": "AZE vs DFM",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "844",
                "ScoreA": "0",
                "TeamB": "555",
                "ScoreB": "1",
                "MatchDate": "2022-05-10 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46254",
                "HighlightsId": "46273",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8856",
                "bMatchName": "ORD vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "845",
                "ScoreA": "0",
                "TeamB": "117",
                "ScoreB": "1",
                "MatchDate": "2022-05-10 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46255",
                "HighlightsId": "46277",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8857",
                "bMatchName": "EG vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "842",
                "ScoreA": "0",
                "TeamB": "117",
                "ScoreB": "1",
                "MatchDate": "2022-05-10 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46256",
                "HighlightsId": "46280",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8858",
                "bMatchName": "IW vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "770",
                "ScoreA": "0",
                "TeamB": "8",
                "ScoreB": "1",
                "MatchDate": "2022-05-10 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46258",
                "HighlightsId": "46284",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8859",
                "bMatchName": "RED vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "779",
                "ScoreA": "1",
                "TeamB": "702",
                "ScoreB": "0",
                "MatchDate": "2022-05-10 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46260",
                "HighlightsId": "46287",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8860",
                "bMatchName": "G2 vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "117",
                "ScoreA": "1",
                "TeamB": "842",
                "ScoreB": "0",
                "MatchDate": "2022-05-11 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46288",
                "HighlightsId": "46304",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8861",
                "bMatchName": "EG vs ORD",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "842",
                "ScoreA": "1",
                "TeamB": "845",
                "ScoreB": "0",
                "MatchDate": "2022-05-11 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46289",
                "HighlightsId": "46307",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8862",
                "bMatchName": "DFM vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "555",
                "ScoreA": "0",
                "TeamB": "843",
                "ScoreB": "1",
                "MatchDate": "2022-05-11 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46290",
                "HighlightsId": "46310",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8863",
                "bMatchName": "AZE vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "844",
                "ScoreA": "0",
                "TeamB": "692",
                "ScoreB": "1",
                "MatchDate": "2022-05-11 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46291",
                "HighlightsId": "46314",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8864",
                "bMatchName": "IW vs RED",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "770",
                "ScoreA": "1",
                "TeamB": "779",
                "ScoreB": "0",
                "MatchDate": "2022-05-11 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46292",
                "HighlightsId": "46318",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8865",
                "bMatchName": "RNG vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "702",
                "ScoreB": "0",
                "MatchDate": "2022-05-11 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46294",
                "HighlightsId": "46323",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8866",
                "bMatchName": "ORD vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "845",
                "ScoreA": "0",
                "TeamB": "842",
                "ScoreB": "1",
                "MatchDate": "2022-05-12 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46338",
                "HighlightsId": "46342",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8867",
                "bMatchName": "G2 vs ORD",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "117",
                "ScoreA": "1",
                "TeamB": "845",
                "ScoreB": "0",
                "MatchDate": "2022-05-12 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46339",
                "HighlightsId": "46345",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8868",
                "bMatchName": "PSG vs IW",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "702",
                "ScoreA": "1",
                "TeamB": "770",
                "ScoreB": "0",
                "MatchDate": "2022-05-12 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46326",
                "HighlightsId": "46348",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8869",
                "bMatchName": "RNG vs RED",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "779",
                "ScoreB": "0",
                "MatchDate": "2022-05-12 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46336",
                "HighlightsId": "46353",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8870",
                "bMatchName": "SGB vs AZE",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "843",
                "ScoreA": "1",
                "TeamB": "844",
                "ScoreB": "0",
                "MatchDate": "2022-05-12 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46334",
                "HighlightsId": "46356",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8871",
                "bMatchName": "T1 vs DFM",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "692",
                "ScoreA": "1",
                "TeamB": "555",
                "ScoreB": "0",
                "MatchDate": "2022-05-12 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46337",
                "HighlightsId": "46359",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8872",
                "bMatchName": "PSG vs RED",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "702",
                "ScoreA": "1",
                "TeamB": "779",
                "ScoreB": "0",
                "MatchDate": "2022-05-13 14:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46360",
                "HighlightsId": "46377",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8873",
                "bMatchName": "RNG vs IW",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "770",
                "ScoreB": "0",
                "MatchDate": "2022-05-13 15:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46363",
                "HighlightsId": "46381",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8874",
                "bMatchName": "IW vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "770",
                "ScoreA": "0",
                "TeamB": "702",
                "ScoreB": "1",
                "MatchDate": "2022-05-13 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46361",
                "HighlightsId": "46384",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8875",
                "bMatchName": "RED vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "779",
                "ScoreA": "0",
                "TeamB": "8",
                "ScoreB": "1",
                "MatchDate": "2022-05-13 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46365",
                "HighlightsId": "46388",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8876",
                "bMatchName": "RED vs IW",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "779",
                "ScoreA": "1",
                "TeamB": "770",
                "ScoreB": "0",
                "MatchDate": "2022-05-13 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46366",
                "HighlightsId": "46391",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8877",
                "bMatchName": "PSG vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "702",
                "ScoreA": "0",
                "TeamB": "8",
                "ScoreB": "1",
                "MatchDate": "2022-05-13 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46368",
                "HighlightsId": "46395",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8878",
                "bMatchName": "EG vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "842",
                "ScoreA": "0",
                "TeamB": "117",
                "ScoreB": "1",
                "MatchDate": "2022-05-14 14:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46405",
                "HighlightsId": "46422",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8879",
                "bMatchName": "EG vs ORD",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "842",
                "ScoreA": "1",
                "TeamB": "845",
                "ScoreB": "0",
                "MatchDate": "2022-05-14 15:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46406",
                "HighlightsId": "46425",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8880",
                "bMatchName": "G2 vs ORD",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "117",
                "ScoreA": "1",
                "TeamB": "845",
                "ScoreB": "0",
                "MatchDate": "2022-05-14 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46398",
                "HighlightsId": "46428",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8881",
                "bMatchName": "G2 vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "117",
                "ScoreA": "1",
                "TeamB": "842",
                "ScoreB": "0",
                "MatchDate": "2022-05-14 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46407",
                "HighlightsId": "46431",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8882",
                "bMatchName": "ORD vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "845",
                "ScoreA": "0",
                "TeamB": "842",
                "ScoreB": "1",
                "MatchDate": "2022-05-14 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46408",
                "HighlightsId": "46434",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8883",
                "bMatchName": "ORD vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "845",
                "ScoreA": "0",
                "TeamB": "117",
                "ScoreB": "1",
                "MatchDate": "2022-05-14 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46409",
                "HighlightsId": "46437",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8884",
                "bMatchName": "AZE vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "760",
                "GameProcName": "第六天",
                "TeamA": "844",
                "ScoreA": "0",
                "TeamB": "843",
                "ScoreB": "1",
                "MatchDate": "2022-05-15 14:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46447",
                "HighlightsId": "46464",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8885",
                "bMatchName": "DFM vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "760",
                "GameProcName": "第六天",
                "TeamA": "555",
                "ScoreA": "0",
                "TeamB": "692",
                "ScoreB": "1",
                "MatchDate": "2022-05-15 15:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46448",
                "HighlightsId": "46467",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8886",
                "bMatchName": "SGB vs DFM",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "760",
                "GameProcName": "第六天",
                "TeamA": "843",
                "ScoreA": "1",
                "TeamB": "555",
                "ScoreB": "0",
                "MatchDate": "2022-05-15 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46449",
                "HighlightsId": "46470",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8887",
                "bMatchName": "T1 vs AZE",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "760",
                "GameProcName": "第六天",
                "TeamA": "692",
                "ScoreA": "1",
                "TeamB": "844",
                "ScoreB": "0",
                "MatchDate": "2022-05-15 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46451",
                "HighlightsId": "46473",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8888",
                "bMatchName": "DFM vs AZE",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "760",
                "GameProcName": "第六天",
                "TeamA": "555",
                "ScoreA": "0",
                "TeamB": "844",
                "ScoreB": "1",
                "MatchDate": "2022-05-15 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46452",
                "HighlightsId": "46476",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8889",
                "bMatchName": "SGB vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "760",
                "GameProcName": "第六天",
                "TeamA": "843",
                "ScoreA": "0",
                "TeamB": "692",
                "ScoreB": "1",
                "MatchDate": "2022-05-15 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46454",
                "HighlightsId": "46478",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8906",
                "bMatchName": "IW vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "770",
                "ScoreA": "0",
                "TeamB": "8",
                "ScoreB": "1",
                "MatchDate": "2022-05-14 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46402",
                "HighlightsId": "46440",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8907",
                "bMatchName": "RNG vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "702",
                "ScoreB": "0",
                "MatchDate": "2022-05-14 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46403",
                "HighlightsId": "46443",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8908",
                "bMatchName": "RNG vs RED",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "19",
                "GameMode": "1",
                "GameTypeName": "小组赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "779",
                "ScoreB": "0",
                "MatchDate": "2022-05-14 22:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46410",
                "HighlightsId": "46446",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8912",
                "bMatchName": "T1 vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "692",
                "ScoreA": "0",
                "TeamB": "117",
                "ScoreB": "1",
                "MatchDate": "2022-05-20 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46479",
                "HighlightsId": "46496",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": " 764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8913",
                "bMatchName": "EG vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "842",
                "ScoreA": "0",
                "TeamB": "8",
                "ScoreB": "1",
                "MatchDate": "2022-05-20 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46481",
                "HighlightsId": "46501",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8914",
                "bMatchName": "PSG vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "702",
                "ScoreA": "1",
                "TeamB": "843",
                "ScoreB": "0",
                "MatchDate": "2022-05-20 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46482",
                "HighlightsId": "46503",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8915",
                "bMatchName": "G2 vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "117",
                "ScoreA": "1",
                "TeamB": "8",
                "ScoreB": "0",
                "MatchDate": "2022-05-20 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46483",
                "HighlightsId": "46508",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8916",
                "bMatchName": "SGB vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "843",
                "ScoreA": "0",
                "TeamB": "842",
                "ScoreB": "1",
                "MatchDate": "2022-05-20 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46484",
                "HighlightsId": "46511",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8917",
                "bMatchName": "PSG vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "710",
                "GameProcName": "第一天",
                "TeamA": "702",
                "ScoreA": "0",
                "TeamB": "692",
                "ScoreB": "1",
                "MatchDate": "2022-05-20 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46486",
                "HighlightsId": "46514",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8918",
                "bMatchName": "G2 vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "117",
                "ScoreA": "1",
                "TeamB": "842",
                "ScoreB": "0",
                "MatchDate": "2022-05-21 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46515",
                "HighlightsId": "46532",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8919",
                "bMatchName": "RNG vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "702",
                "ScoreB": "0",
                "MatchDate": "2022-05-21 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46517",
                "HighlightsId": "46535",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8920",
                "bMatchName": "T1 vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "692",
                "ScoreA": "1",
                "TeamB": "843",
                "ScoreB": "0",
                "MatchDate": "2022-05-21 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46518",
                "HighlightsId": "46538",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8921",
                "bMatchName": "PSG vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "702",
                "ScoreA": "0",
                "TeamB": "842",
                "ScoreB": "1",
                "MatchDate": "2022-05-21 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46519",
                "HighlightsId": "46541",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8922",
                "bMatchName": "RNG vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "692",
                "ScoreB": "0",
                "MatchDate": "2022-05-21 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46521",
                "HighlightsId": "46547",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8923",
                "bMatchName": "SGB vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "720",
                "GameProcName": "第二天",
                "TeamA": "843",
                "ScoreA": "0",
                "TeamB": "117",
                "ScoreB": "1",
                "MatchDate": "2022-05-21 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46523",
                "HighlightsId": "46550",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8924",
                "bMatchName": "EG vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "842",
                "ScoreA": "0",
                "TeamB": "692",
                "ScoreB": "1",
                "MatchDate": "2022-05-22 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46551",
                "HighlightsId": "46568",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8925",
                "bMatchName": "G2 vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "117",
                "ScoreA": "0",
                "TeamB": "702",
                "ScoreB": "1",
                "MatchDate": "2022-05-22 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46552",
                "HighlightsId": "46571",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8926",
                "bMatchName": "RNG vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "843",
                "ScoreB": "0",
                "MatchDate": "2022-05-22 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46554",
                "HighlightsId": "46575",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8927",
                "bMatchName": "T1 vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "692",
                "ScoreA": "1",
                "TeamB": "702",
                "ScoreB": "0",
                "MatchDate": "2022-05-22 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46555",
                "HighlightsId": "46577",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": " 764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8928",
                "bMatchName": "RNG vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "117",
                "ScoreB": "0",
                "MatchDate": "2022-05-22 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46557",
                "HighlightsId": "46580",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": " 764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8929",
                "bMatchName": "EG vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "730",
                "GameProcName": "第三天",
                "TeamA": "842",
                "ScoreA": "1",
                "TeamB": "843",
                "ScoreB": "0",
                "MatchDate": "2022-05-22 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46559",
                "HighlightsId": "46583",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8930",
                "bMatchName": "PSG vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "702",
                "ScoreA": "1",
                "TeamB": "117",
                "ScoreB": "0",
                "MatchDate": "2022-05-23 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46584",
                "HighlightsId": "46602",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8931",
                "bMatchName": "T1 vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "692",
                "ScoreA": "0",
                "TeamB": "842",
                "ScoreB": "1",
                "MatchDate": "2022-05-23 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46586",
                "HighlightsId": "46606",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8932",
                "bMatchName": "SGB vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "843",
                "ScoreA": "0",
                "TeamB": "8",
                "ScoreB": "1",
                "MatchDate": "2022-05-23 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46588",
                "HighlightsId": "46611",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8933",
                "bMatchName": "G2 vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "117",
                "ScoreA": "0",
                "TeamB": "692",
                "ScoreB": "1",
                "MatchDate": "2022-05-23 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46589",
                "HighlightsId": "46615",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8934",
                "bMatchName": "SGB vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "843",
                "ScoreA": "1",
                "TeamB": "702",
                "ScoreB": "0",
                "MatchDate": "2022-05-23 20:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46590",
                "HighlightsId": "46618",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8935",
                "bMatchName": "RNG vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "740",
                "GameProcName": "第四天",
                "TeamA": "8",
                "ScoreA": "1",
                "TeamB": "842",
                "ScoreB": "0",
                "MatchDate": "2022-05-23 21:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46592",
                "HighlightsId": "46623",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8936",
                "bMatchName": "G2 vs SGB",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "117",
                "ScoreA": "0",
                "TeamB": "843",
                "ScoreB": "1",
                "MatchDate": "2022-05-24 14:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46624",
                "HighlightsId": "46642",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8937",
                "bMatchName": "EG vs PSG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "842",
                "ScoreA": "1",
                "TeamB": "702",
                "ScoreB": "0",
                "MatchDate": "2022-05-24 15:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46626",
                "HighlightsId": "46648",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8938",
                "bMatchName": "SGB vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "843",
                "ScoreA": "0",
                "TeamB": "692",
                "ScoreB": "1",
                "MatchDate": "2022-05-24 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46627",
                "HighlightsId": "46651",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8939",
                "bMatchName": "PSG vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "702",
                "ScoreA": "0",
                "TeamB": "8",
                "ScoreB": "1",
                "MatchDate": "2022-05-24 17:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46629",
                "HighlightsId": "46655",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8940",
                "bMatchName": "EG vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "842",
                "ScoreA": "0",
                "TeamB": "117",
                "ScoreB": "1",
                "MatchDate": "2022-05-24 18:00:00",
                "MatchStatus": "3",
                "MatchWin": "2",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46631",
                "HighlightsId": "46659",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8941",
                "bMatchName": "T1 vs RNG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "55",
                "GameMode": "1",
                "GameTypeName": "对抗赛",
                "GameProcId": "750",
                "GameProcName": "第五天",
                "TeamA": "692",
                "ScoreA": "1",
                "TeamB": "8",
                "ScoreB": "0",
                "MatchDate": "2022-05-24 19:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46633",
                "HighlightsId": "46664",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8942",
                "bMatchName": "RNG vs EG",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "18",
                "GameMode": "4",
                "GameTypeName": "淘汰赛",
                "GameProcId": "880",
                "GameProcName": "半决赛",
                "TeamA": "8",
                "ScoreA": "3",
                "TeamB": "842",
                "ScoreB": "0",
                "MatchDate": "2022-05-27 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46668",
                "HighlightsId": "46686",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8943",
                "bMatchName": "T1 vs G2",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "18",
                "GameMode": "4",
                "GameTypeName": "淘汰赛",
                "GameProcId": "880",
                "GameProcName": "半决赛",
                "TeamA": "692",
                "ScoreA": "3",
                "TeamB": "117",
                "ScoreB": "0",
                "MatchDate": "2022-05-28 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46690",
                "HighlightsId": "46704",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            },
            {
                "bMatchId": "8944",
                "bMatchName": "RNG vs T1",
                "GameId": "175",
                "GameName": "2022季中冠军赛",
                "GameTypeId": "18",
                "GameMode": "4",
                "GameTypeName": "淘汰赛",
                "GameProcId": "890",
                "GameProcName": "决赛",
                "TeamA": "8",
                "ScoreA": "3",
                "TeamB": "692",
                "ScoreB": "2",
                "MatchDate": "2022-05-29 16:00:00",
                "MatchStatus": "3",
                "MatchWin": "1",
                "iQTMatchId": "0",
                "bGameId": "8",
                "NewsId": "46712",
                "HighlightsId": "46732",
                "Video1": "0",
                "Video2": "0",
                "Video3": "764502578",
                "Chat1": "",
                "Chat2": "",
                "Chat3": "764502578",
                "News1": "",
                "News2": "",
                "News3": "",
                "isFocus": "1"
            }
        ]
    }
};